### ISSUE TITLE
Spacing 

### ISSUE THREAD

**Issue by Pixappsimon** [Pixappsimon/SoumissionPiscine#4]
![exemple](https://cloud.githubusercontent.com/assets/26634830/24839790/f571be8c-1d2e-11e7-985c-098705e650fc.png)

**Comment by Pixappsimon** [comment]
Rajout d'espace

**Comment by frankybboy96** [comment]
Augmenté la grandeur a 52%, était 48%

Vérifié avec le client si les nouvelles grandeurs sont satisfaisante
